name = "SparsityTracing"
uuid = "06eadbd4-12ad-4cbc-ab6e-10f8370940a5"
authors = ["Stuart Daines <stuart.daines@gmail.com>"]
version = "0.2.5"

[deps]
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
DiffRules = "1"
Documenter = "0.27, 1"
SpecialFunctions = "1, 2"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Logging", "LinearAlgebra"]
